<?php

use Illuminate\Database\Seeder;

class OrderTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('orders')->insert([
            [
                'user_id' => 1,
                'address_name' => '山田花子',
                'postal_code' => '0098765',
                'address' => '千葉県浦安市舞浜１−１',
                'phone_number' => '08012345678',
                'order_status' => 1,
                'memo' => 'なし',
                'reception_time' => now(),
                'shipping_time' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'address_name' => '煉獄杏寿郎',
                'postal_code' => '0012345',
                'address' => '東京都港区芝公園４丁目２−８',
                'phone_number' => '08098765432',
                'order_status' => 1,
                'memo' => 'なし',
                'reception_time' => now(),
                'shipping_time' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'address_name' => '山田花子',
                'postal_code' => '0098765',
                'address' => '千葉県浦安市舞浜１−１',
                'phone_number' => '08012345678',
                'order_status' => 1,
                'memo' => 'なし',
                'reception_time' => now(),
                'shipping_time' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'address_name' => '煉獄杏寿郎',
                'postal_code' => '0012345',
                'address' => '東京都港区芝公園４丁目２−８',
                'phone_number' => '08098765432',
                'order_status' => 1,
                'memo' => 'なし',
                'reception_time' => now(),
                'shipping_time' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'address_name' => '山田花子',
                'postal_code' => '0098765',
                'address' => '千葉県浦安市舞浜１−１',
                'phone_number' => '08012345678',
                'order_status' => 2,
                'memo' => 'なし',
                'reception_time' => now(),
                'shipping_time' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'address_name' => '煉獄杏寿郎',
                'postal_code' => '0012345',
                'address' => '東京都港区芝公園４丁目２−８',
                'phone_number' => '08098765432',
                'order_status' => 2,
                'memo' => 'なし',
                'reception_time' => now(),
                'shipping_time' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'address_name' => '山田花子',
                'postal_code' => '0098765',
                'address' => '千葉県浦安市舞浜１−１',
                'phone_number' => '08012345678',
                'order_status' => 3,
                'memo' => 'なし',
                'reception_time' => now(),
                'shipping_time' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'address_name' => '煉獄杏寿郎',
                'postal_code' => '0012345',
                'address' => '東京都港区芝公園４丁目２−８',
                'phone_number' => '08098765432',
                'order_status' => 3,
                'memo' => 'なし',
                'reception_time' => now(),
                'shipping_time' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'address_name' => '山田花子',
                'postal_code' => '0098765',
                'address' => '千葉県浦安市舞浜１−１',
                'phone_number' => '08012345678',
                'order_status' => 4,
                'memo' => 'なし',
                'reception_time' => now(),
                'shipping_time' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => 1,
                'address_name' => '煉獄杏寿郎',
                'postal_code' => '0012345',
                'address' => '東京都港区芝公園４丁目２−８',
                'phone_number' => '08098765432',
                'order_status' => 4,
                'memo' => 'なし',
                'reception_time' => now(),
                'shipping_time' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
